### PR TITLE
add build folder to .gitignore and fix pep8

### PR DESCRIPTION
**Pull request by eamanu**
Add /build folder to gitignore

### CODE REVIEW

**Comment by CMB** [comment]
Emmanuel Arias <notifications@github.com> writes:

> Add /build folder to gitignore

Thank you for the PR.  I'll merge it, including your PEP8 fixes.

A bit of history here: I didn't have any stylistic conventions when I
started this project.  A friend of mine basically decided that we should
use Gentoo's Python coding style, and they sent me a patch to switch
over to that.  I've never been terribly happy with that choice, but I
didn't really want to add a commit just for a huge style change.  Well
now it's done.

I do have one question:

diff --git a/bin/cligh b/bin/cligh
index f698ee4..e774fa3 100755
--- a/bin/cligh
+++ b/bin/cligh
@@ -1,6 +1,13 @@
 #!/usr/bin/env python3
 """Simple command-line interface to github."""
 # See the file LICENSE for copyright and license info.
+__author__ = "Chris Brannon <chris@the-brannons.com>"
+__copyright__ = "See the file LICENSE for copyright and license info"
+__license__ = "See the file LICENSE for copyright and license info"
+__version__ = "0.3.2"
+__maintainer__ = "Emmanuel Arias <eamanu@eamanu.com>"
+__email__ = "chris@the-brannons.com, eamanu@eamanu.com"
+

Are you wanting to maintain cligh, then?  And where did you get version
0.3.2?  There hasn't been a version 0.3.1 yet, to the best of my
knowledge.

-- Chris

**Comment by eamanu** [comment]
Hello, 

Thanks for you response. 

I am new in Debian project. I see your package in WNPP. I thought that cligh is a interest package so, I send the request for take the package (in Debian). In tracker.debian  see that cligh have the 0.3.1 version tag. For this reason I put the `__version__= 0.3.2`. 

I don't know if you like the `__maintainer__ = "Emmanuel Arias <eamanu@eamanu.com>"`, I can erase this line, and let the "Maintainer" in debian package's files.

Regards

**Comment by CMB** [comment]
Emmanuel Arias <notifications@github.com> writes:

> Hello,
>
> Thanks for you response.
>
> I am new in Debian project. I see your package in WNPP. I thought that cligh is a interest package so, I send the request for
> take the package (in Debian). In tracker.debian see that cligh have the 0.3.1 version tag. For this reason I put the
> __version__= 0.3.2.

Hello,
I looked, and I see that their version is 0.3-1 and not 0.3.1.  So
probably just 0.3 should go in the version string; the -1 is for
Debian's use.

> I don't know if you like the __maintainer__ = "Emmanuel Arias <eamanu@eamanu.com>", I can erase this line, and let the
> "Maintainer" in debian package's files.

Yeah, for now I'd suggest doing that.  If you want to take over
maintainership of the upstream cligh codebase, we can discuss that
sometime.

-- Chris

**Comment by eamanu** [comment]
Done!

**Pull request merged**
